namespace trungtamdaotao.Models
{
    // CourseRevenue class represents the revenue generated by a course in the training center.
    // It contains properties for course ID, name, number of enrollments, tuition fee, and total revenue.
    // This class is used to calculate and display the financial performance of courses.
public class CourseStudentStats
{
    public int CourseId { get; set; }
    public string CourseName { get; set; }
    public int TotalStudents { get; set; }
}
}
